[build-system]
requires = ["setuptools>=64", "wheel", "setuptools_scm>=8.1"]
build-backend = "setuptools.build_meta"

[project]
name = "chemrixs"
authors = [
    {name = "Amke Nimmrich", email = "animmri@uw.edu"},
    {name = "Bryna Hazelton", email = "brynah@phys.washington.edu"},
]
maintainers = [
    {name = "Amke Nimmrich", email = "animmri@uw.edu"},
]
description = "Python objects and interfaces for processing and analysing data recorded at the chemRIXS instrument at LCLS"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "dask",
    "h5py>=3.7",
    "ipympl",
    "jupyter",
    "matplotlib",
    "numpy>=1.23",
    "psutil",
    "python>=3.11",
    "scipy>=1.9"
]
requires-python = ">=3.11"
keywords = ["ultrafast X-ray spectroscopy"]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Astronomy",
]

[project.optional-dependencies]
doc = ["sphinx"]


[project.urls]
Repository = "https://github.com/AmkeNimm/DataAcceleratorChemRIXS"
Documentation = "https://github.com/AmkeNimm/DataAcceleratorChemRIXS/docs"

